# baseURL: "https://rault-cettes.elenetgreg.fr/"
title: Rault-cettes / Recettes
paginate: 5
theme: PaperMod

defaultContentLanguage: fr

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


frontmatter:
  date:
  - :filename
  - :default

# googleAnalytics: UA-123-45
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

  
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
