
env: production # to enable google analytics, opengraph, twitter-cards and schema.
title: Rault-cettes / Recettes
description: "Des recettes"
keywords: [Blog, Portfolio, PaperMod]
author: Elen et Greg
# author: ["Me", "You"] # multiple authors
images: ["<link or path of image for opengraph, twitter-cards>"]
DateFormat: "2 January  2006"
defaultTheme: auto # dark, light
disableThemeToggle: false

ShowReadingTime: false
ShowShareButtons: false
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: false
disableSpecial1stPost: false
disableScrollToTop: false
comments: false
hidemeta: false
hideSummary: false
showtoc: false
tocopen: false

assets:
  # disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: "<link / abs url>"
  favicon16x16: "<link / abs url>"
  favicon32x32: "<link / abs url>"
  apple_touch_icon: "<link / abs url>"
  safari_pinned_tab: "<link / abs url>"

label:
  text: "Rault-cettes/Recettes"
  # icon: /apple-touch-icon.png
  iconHeight: 35

# profile-mode
# profileMode:
#   enabled: false # needs to be explicitly set
#   title: ExampleSite
#   subtitle: "This is subtitle"
#   imageUrl: "<img location>"
#   imageWidth: 120
#   imageHeight: 120
#   imageTitle: my image
#   buttons:
#     - name: Posts
#       url: posts
#     - name: Tags
#       url: tags

# home-info mode
homeInfoParams:
  Title: "🍰"
  Content: Quelques recettes de 🍰 et de 🍲...

socialIcons:
  # - name: twitter
  #   url: "https://twitter.com/"
  # - name: stackoverflow
  #   url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/genuinegreg/rault-cettes"

analytics:
  # google:
  #   SiteVerificationTag: "XYZabc"
  # bing:
  #   SiteVerificationTag: "XYZabc"
  # yandex:
  #   SiteVerificationTag: "XYZabc"

cover:
  hidden: true # hide everywhere but not in structured data
  hiddenInList: false # hide on list pages and home
  hiddenInSingle: false # hide on single page
  relative: true

editPost:
  URL: "https://github.com/genuinegreg/rault-cettes/blob/master/content"
# https://github.com/genuinegreg/rault-cettes/blob/master/content/posts/brioche.md
  Text: "Suggest Changes" # edit text
  appendFilePath: true # to append file path to Edit link

# for search
# https://fusejs.io/api/options.html
fuseOpts:
  isCaseSensitive: false
  shouldSort: true
  location: 0
  distance: 1000
  threshold: 0.4
  minMatchCharLength: 0
  keys: ["title", "permalink", "summary", "content"]