version: "3"
services: 
  build:
    image: klakegg/hugo:0.95.0
    volumes:
      - ".:/src"
  server:
    image: klakegg/hugo:0.95.0
    command: server --baseURL "http://pi.hole"
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"